language: cpp
compiler: gcc
# command to install dependencies
install: 
  - curl http://epics.nsls2.bnl.gov/debian/repo-key.pub | sudo apt-key add -
  - echo "deb http://epics.nsls2.bnl.gov/debian/ wheezy main contrib" | sudo tee -a /etc/apt/sources.list
  - echo "deb-src http://epics.nsls2.bnl.gov/debian/ wheezy main contrib" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install epics-dev
  - env | grep -i epics
  - caget -h
# command to run tests
script: caget -h

