language: cpp
compiler: gcc
# command to install dependencies
install: 
  - curl http://epics.nsls2.bnl.gov/debian/repo-key.pub | sudo apt-key add -
  - echo "deb http://epics.nsls2.bnl.gov/debian/ wheezy/staging main contrib" | sudo tee -a /etc/apt/sources.list
  - echo "deb-src http://epics.nsls2.bnl.gov/debian/ wheezy/staging main contrib" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install epics-dev epics-synapps-dev aravis0.2 epics-areadetector-dev
  - env | grep -i epics
  - which caget
  - ls -l /usr/lib
  - ls -l /usr/include
  - ls -l /usr/bin
# command to run tests
script: echo "all done"

