language: c++

env: 
  global:
    - EPICS_BASE=/path/to/base
  matrix:
    - EPICS_VERSION=R3.14.12.3
    - EPICS_VERSION=R3.15.3

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      
    - os: linux
      dist: precise
      sudo: false
      
    - os: osx
      osx_image: xcode7.2

before_install:
  - echo ${EPICS_VERSION}

install:
  - echo "Building"

script:
  - echo "Running tests"

